# 예외 처리
## 예외 처리 방법
파이썬에서는 try-except 구문을 제공한다.
### 구조
```
# try-except 구문의 기본 구조
try:
    ...
except 오류 사항 as 오류 메시지 변수:
    ...
finally:
    ...
```
* try 구문
  * 오류 발생 가능성이 있는 코드를 넣는다.
* catch 구문
  * try 구분 내의 코드에서 예외 발생시 바로 이 구문으로 코드 흐름이 점프한다.
  * 예외 발생시 처리할 수 있는 코드를 넣는다.
* finally 구문
 * 예외 발생 여부와 상관없이 항상 실행된다.
 * 보통 리소스 반납같은 코드가 여기에 존재한다.
### 예외 처리 코드 흐름
* try 내 코드 정상 수행시 : try --> finally
* try 내 코드 예외 발생시 : try --> catch --> finally
### 예제
#### 하나의 예외 처리
```
try:
    res = 10 / 0 # 0으로 나눌 수 없다.
    print(res)
except Exception as e:
    print(e)

# division by zero
```
#### 여러 개의 예외 처리
```
try:
    res = 10 / 'zero'
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)

# unsupported operand type(s) for /: 'int' and 'str'
```
#### finally 사용
```
def add(a, b):
    try:
        res = a + b
    except Exception as e:
        print(e)
    finally:
        print("finally")
    return res


# try문 정상 수행
res1 = add(1, 2)
print(res1)

# finally
# 3

# try문 예외 발생
res2 = add(1, 'zero')

# unsupported operand type(s) for +: 'int' and 'str'
# finally
```
## 오류 회피하기
특정 오류가 발생할 경우 통과시킬 수 있다.
```
try:
    f = open("없는 파일", 'r')
except FileNotFoundError:
    pass
```
try문 안에서 FileNotFoundError가 발생할 경우에 pass를 사용하여 오류를 그냥 회피하도록 작성한 예제이다.
## 예외 만들기 & 오류 발생 시키기
### 예외 만들기
파이썬 내장 클래스인 Exception 클래스를 상속하여 만들 수 있다.
### 오류 발생 시키기
raise 명령어를 사용해 오류를 강제로 발생시킬 수 있다.

```
# 예외 만들기
class HandMadeError(Exception):
    pass

# 오류 발생 시키기
def raiseError():
    raise HandMadeError()

raiseError() # __main__.HandMadeError
```